name: new_version
description: Check if your user has the most recent version of your Flutter app.
version: 0.3.1
homepage: https://github.com/timtraversy/new_version

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  package_info_plus: ^8.1.1
  http: ^1.2.2
  html: ^0.15.4
  url_launcher: ^6.3.1
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
